### ISSUE TITLE
A required library is missing in the AppImage

### ISSUE THREAD

**Issue by probonopd** [alkatrazstudio/meson-player#1]
Hi, thanks for making an AppImage. Cool!
A required library is missing in the AppImage, please bundle it.

```
/run/firejail/appimage/.appimage-9306/AppRun: error while loading shared libraries: libxcb-keysyms.so.1: cannot open shared object file: No such file or directory
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/2014

**Comment by z80maniac** [comment]
Added `libxcb-keysyms.so` to the CI build:
https://github.com/alkatrazstudio/meson-player/releases/tag/edge-dev

The bundled library will be used as a fallback when the system library is not found.
